# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def gen_fib():
    fib_prev = 1
    fib_curr = 1
    while True:
        yield fib_curr
        fib_aux = fib_curr
        fib_curr += fib_prev
        fib_prev = fib_aux
        
def prob_2(limit = 4_000_000):
    even_sum = 0
    for fib in gen_fib():
        if fib >= limit:
            return even_sum
        if fib % 2 == 0:
            even_sum += fib

print(prob_2())